### ISSUE TITLE
Allow overriding the sytemMessage in chatgpt

### ISSUE THREAD

**Issue by maczikasz** [shiftEscape/firebase-extensions#2]
This extension is awesome saves much time from having to implement a backend. It would be however amazing if it was possible to override the systemMessage of the chatgpt lib. It would allow creating a focused chatbot and not a general purpose one

**Comment by shiftEscape** [comment]
Hello @bensilone , the new update on this will be included on version `0.1.0`. Currently it is under review by Google. Stay tuned for updates!
